import { defineComponent } from 'vue';
import s from './EmojiSelect.module.scss';

export const EmojiSelect = defineComponent({
    setup(props, context) {
        return () => (
            <div class={s.wrapper}>
                <nav>
                    <span class={s.selected}>表情</span>
                    <span>手势</span>
                    <span>职业</span>
                    <span>衣服</span>
                    <span>动物</span>
                    <span>自然</span>
                    <span>食物</span>
                    <span>运动</span>
                    <span>表情</span>
                    <span>手势</span>
                    <span>职业</span>
                    <span>衣服</span>
                    <span>动物</span>
                    <span>自然</span>
                    <span>食物</span>
                    <span>运动</span>
                </nav>
                <ol>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                    <li>😀</li>
                </ol>
            </div>
        )
    }
})